### ISSUE TITLE
rename project

### ISSUE THREAD

**Issue by chunhualiao** [bin123apple/Fortran2Cpp#4]
"Fortran2Cpp", and "the Fortran2Cpp translator" are better names (without a hypen).

C in F2C can mislead readers to believe that we are translating into C programming language. 

I suggest to use this pair of names (short vs. full name) for your work from now on.

If this makes sense to you, you may need to change your github and huggingface repo names to reflect this change (Fortran2Cpp).

**Comment by bin123apple** [comment]
I just finished updating the name in Github. However the name of the huggingface repo can not be changed. I updated the name inside the README of the huggingface repo to avoid potential misleading.

**Comment by chunhualiao** [comment]
> I just finished updating the name in Github. However the name of the huggingface repo can not be changed. I updated the name inside the README of the huggingface repo to avoid potential misleading.

For huggingface repo, you can create a new repo with the right name and delete the old repo.  otherwise the F2C-translator URL on huggingface is misleading.

**Comment by bin123apple** [comment]
Thanks for the suggestion, I just created a new Huggingface repo and updated the README.

**Comment by chunhualiao** [comment]
this seems to be done
