### ISSUE TITLE
v1 datasets: store a version in human readable format

### ISSUE THREAD

**Issue by chunhualiao** [bin123apple/Fortran2Cpp#50]
V1 dataset has 2500? pairs of Fortran vs. C++ codes. 

People would be interested in seeing these pairs in human readable formats: paired source files like  file001.f90 vs file001.cpp. 

Then we can do manual evaluation of the quality of the datasets. 

Could you please generate these files from your v1. dataset and save into a folder of this repo? 

This helps me answer question like: how complex are the code in the dataset next Tuesday.

**Comment by bin123apple** [comment]
@chunhualiao @peihunglin @LChenGit I just uploaded the readable format dataset under data/readable_format

**Comment by chunhualiao** [comment]
Great! This is a good progress. 

However, to answer the question "how complex are the code",  could you please plot a distribution of the number of files of certain source line counts, for the Fortran version?   Please add the plots to the paper.  It is a histogram, the y-axis is the file counts. The X axis is the line numbers or ranges of line numbers.   The C++ version's histogram is also valuable. Looking at both can help evaluate if the distributions match (or there are some problems for the paired translation).  

For a paper with a contribution of a new dataset,  such dataset statistics are needed anyway. @bin123apple

**Comment by bin123apple** [comment]
Thanks for the suggestion. I just uploaded two new figures (**figure3 & 4**) in the overleaf.

These two figures contains:

> distribution of the number of files of certain source line counts

In case you want to modify the figure, the code for plotting the figure is in `data/distribution_plot.py`.

**Comment by chunhualiao** [comment]
![image](https://github.com/user-attachments/assets/368a1e3a-befb-4ee0-80c9-dd021d74b75e)
