### ISSUE TITLE
Minimal GPU memory needed to run fine-tuned deepseek-coder-33b-instruct?

### ISSUE THREAD

**Issue by chunhualiao** [bin123apple/Fortran2Cpp#6]
User may need this information to check if they have enough GPU resources.

**Comment by bin123apple** [comment]
It is shown in the **Hardware requirements** parts (_We used 6 A100 GPUs with 80GB memory for the training_).

**Comment by chunhualiao** [comment]
I asked for ***minimal*** gpu memory for **+inference***.

You respond with the configration for training. 

Do you think we are taking about the same thing?

**Comment by bin123apple** [comment]
For the inference, the information is also shown in the **Hardware requirements** part (_We used 2 A100 GPUs with 80GB memory for the inference_.)
