### ISSUE TITLE
CodeQwen 1.5 

### ISSUE THREAD

**Issue by chunhualiao** [bin123apple/Fortran2Cpp#8]
https://qwenlm.github.io/blog/codeqwen1.5/
* 7B,
* 63k context window

This model is specially designed for coding. 

<img width="576" alt="image" src="https://github.com/bin123apple/Fortran2Cpp/assets/1627206/f8f22da2-4cc5-4561-95ef-1820b328f3a3">

You may consider adding this new one. If you have too many models, you can replace some old one.  

The LiveCodeBench results show that CodeQwen 7B is close to WizardCoder-33B and Deepseek-Ins-33B. Quite impressive. Using smaller 7-B model may speed up your self-teaching pipeline.

**Comment by chunhualiao** [comment]
![image](https://github.com/bin123apple/Fortran2Cpp/assets/1627206/5ba0fa18-23af-4daf-92be-2531b321686f)

**Comment by bin123apple** [comment]
Sure! I will have a look.
